### ISSUE TITLE
anyway to support android?

### ISSUE THREAD

**Issue by fastcoding** [WuBingzheng/libleak#12]
I replaced backtrace implementation with libunwind to make it built with the latest ndk. however when tested on a Huawei P9 mobile phone(android 8/api 28/arm64-v8a), it always crash with bus error on startup.

**Comment by WuBingzheng** [comment]
I am afraid I can not help, because I do not have any mobile development experience.

Where source code does the process crash at? Does it crash in libleak?

**Comment by fastcoding** [comment]
Not quite sure, because it always crashes during program loading. even the gdbserver will die after hooking up libleak.so.

Because backtrace() api is not available on android, , I have to use libunwind to implement backtrace and this modification brings in the dependency to libc++_shared.so. 

then I test the patched libleak from adb shell like this:
LD_PRELOAD="/data/local/tmp/libc++_shared.so /data/local/tmp/libleak.so"  LEAK_EXPIRE=2 /data/local/tmp/testprog
>>Bus error 

I need a small tool to locate the memory leak in one of my android app which contains both java and native codes. The solutions provided google look not much useful. For example,I tested the malloc debug setting, once I set backtrace in options, the program will run unacceptably very slow and the worst is it will be killed by system eventually.

I need a way to customize the backtrace. maybe libleak can help if it can be ported to android's linux. 

Thanks for your reply.

**Comment by WuBingzheng** [comment]
I can not port it to android, I even do not know how to setup a development environment.
Besides, I do not know Java, or if libleak works with Java.

libleak is for the ones who can not change the target program's source code.
If you can change, I think malloc's debug hook is better because it's much simpler.

It makes you program very slow, may because your program calls malloc() too often and backtrace() is expensive. libleak would be the same if it works.

I am sorry I can not help any more.
